#!/usr/bin/env bash
# picklist-ops/lib/print.sh — Picklist print dispatch and vault archive
# Requires: core.sh, marketplace-lib/alerts.sh sourced first

# ── picklist_dispatch <batch_id> <html_file> ─────────────────────────────
# Primary dispatch: archive to vault + optionally print via CUPS.
# Call this after generating the HTML with picklist_generate_html.
picklist_dispatch() {
  local batch_id="$1"
  local html_file="$2"

  log "picklist_dispatch: dispatching ${batch_id}"

  # 1. Archive to Obsidian vault
  picklist_vault_archive "$batch_id" "$html_file"

  # 2. Physical print via CUPS (if printer configured)
  if [[ -n "${PICKLIST_PRINTER_NAME:-}" ]]; then
    picklist_cups_print "$batch_id" "$html_file" "$PICKLIST_PRINTER_NAME"
  else
    log "picklist_dispatch: PICKLIST_PRINTER_NAME not set — skipping physical print"
  fi
}

# ── picklist_vault_archive <batch_id> <html_file> ─────────────────────────
# Write a markdown summary of the picklist to the Obsidian vault.
# The full HTML is stored locally at PICKLIST_PRINTS_DIR; the vault gets
# a lightweight summary note that links to the batch for traceability.
picklist_vault_archive() {
  local batch_id="$1"
  local html_file="$2"

  local batch_json
  batch_json=$(picklist_batch_load "$batch_id" 2>/dev/null || echo "{}")

  local order_count mode created_at
  order_count=$(printf '%s' "$batch_json" | jq -r '.order_count // "?"')
  mode=$(printf '%s' "$batch_json" | jq -r '.mode // "unknown"')
  created_at=$(printf '%s' "$batch_json" | jq -r '.created_at // ""')

  local order_ids_list
  order_ids_list=$(printf '%s' "$batch_json" | jq -r '.order_ids // [] | join(", ")')

  local date_str
  date_str=$(date '+%Y-%m-%d')

  local content
  content=$(cat <<MDEOF
---
source: picklist-ops
type: picklist
batch_id: ${batch_id}
mode: ${mode}
order_count: ${order_count}
date: ${date_str}
created_at: ${created_at}
status: generated
---

# Picklist ${batch_id}

**Mode:** ${mode}
**Orders:** ${order_count}
**Generated:** ${created_at}

## Orders in This Batch

${order_ids_list}

## Actions

- Print HTML: available at \`${html_file}\`
- On return: scan QR code on picklist to trigger shipping label auto-print

---
*Auto-generated by picklist-ops*
MDEOF
)

  vault_write "07-Marketplace/Warehouse/Picklists/${date_str}-${batch_id}.md" "$content" || \
    log "picklist_vault_archive: vault write failed for ${batch_id}"
}

# ── picklist_cups_print <batch_id> <html_file> <printer_name> ────────────
# Print the picklist to a CUPS printer.
# Tries wkhtmltopdf → chromium headless → lp direct (HTML) in order of preference.
picklist_cups_print() {
  local batch_id="$1"
  local html_file="$2"
  local printer="$3"

  local pdf_file="${PICKLIST_PRINTS_DIR}/${batch_id}.pdf"

  # Try wkhtmltopdf first
  if command -v wkhtmltopdf &>/dev/null; then
    log "picklist_cups_print: converting via wkhtmltopdf"
    wkhtmltopdf --quiet --page-size A4 "$html_file" "$pdf_file" 2>/dev/null
    if [[ -f "$pdf_file" ]]; then
      lp -d "$printer" "$pdf_file" && \
        log "picklist_cups_print: printed ${batch_id} to ${printer} (wkhtmltopdf)" && return 0
    fi
  fi

  # Try Chromium headless
  local chromium_bin
  chromium_bin=$(command -v chromium-browser || command -v chromium || command -v google-chrome || echo "")
  if [[ -n "$chromium_bin" ]]; then
    log "picklist_cups_print: converting via chromium headless"
    "$chromium_bin" \
      --headless --disable-gpu --no-sandbox \
      --print-to-pdf="$pdf_file" \
      "file://${html_file}" 2>/dev/null
    if [[ -f "$pdf_file" ]]; then
      lp -d "$printer" "$pdf_file" && \
        log "picklist_cups_print: printed ${batch_id} to ${printer} (chromium)" && return 0
    fi
  fi

  # Fall back to printing HTML directly (some CUPS setups support this)
  if command -v lp &>/dev/null; then
    log "picklist_cups_print: printing HTML directly via lp"
    lp -d "$printer" "$html_file" && \
      log "picklist_cups_print: printed ${batch_id} to ${printer} (lp direct)" && return 0
  fi

  log "picklist_cups_print: WARN — could not print ${batch_id} (no wkhtmltopdf/chromium/lp)"
  return 1
}
